// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Episodes         string
	Seasons          string
	Works            string
	PrismaMigrations string
}{
	Episodes:         "Episodes",
	Seasons:          "Seasons",
	Works:            "Works",
	PrismaMigrations: "_prisma_migrations",
}
